### ISSUE TITLE
你好,小小影视薅羊毛稳定吗? 

### ISSUE THREAD

**Issue by lxk0301** [photonmang/quantumultX#2]
小小影视发现是100块钱才能提现

不知作者这边有提现过了吗?

**Comment by photonmang** [comment]
> 小小影视发现是100块钱才能提现
> 
> 不知作者这边有提现过了吗?

第一次提现根据小小影视管理的说法，需要有一个以上的邀请并且保持日活。那就能提现。具体能不能提现我还差一点点。上次提现了50多元审核通过了，但是小小影视管理说新版本要100元，让我更新版本后在新版本里提现，所以具体后续还能不能给，再等几天我就满100元了就能知道结果了。另外之前说的50元审核通过没有打款的说会让技术退回给我，目前我还未收到。

**Comment by lxk0301** [comment]
好的， 多谢解答
