### ISSUE TITLE
大佬，新版的免广告失效了，建议如下修改一下。。。

### ISSUE THREAD

**Issue by GB-png** [photonmang/quantumultX#3]
/*QX:
https:\/\/.*\..*\.com\/(ssp-svr\/ssp\/|ucp/index) url script-response-body xxys.js
MITM = *.xxjjappss.com,acf.huaerdadi.com
*/
const path1 = "/ucp/index";
const ad = 'list3';
let obj = JSON.parse($response.body);

if ($request.url.indexOf(path1) != -1){
	obj.data.uinfo["down_daily_remainders"] = "666";
	obj.data.uinfo["play_daily_remainders"] = "666";
	obj.data.uinfo["curr_group"] = "5";
	obj.data.user["isvip"] = "1";
	obj.data.user["goldcoin"] = "666";
}

if ($request.url.indexOf(ad) != -1) {
delete obj.data.pmap
}
$done({body: JSON.stringify(obj)});

**Comment by photonmang** [comment]
> /_QX: https://._..*.com/(ssp-svr/ssp/|ucp/index) url script-response-body xxys.js
> MITM = *.xxjjappss.com,acf.huaerdadi.com
> */
> const path1 = "/ucp/index";
> const ad = 'list3';
> let obj = JSON.parse($response.body);
> 
> if ($request.url.indexOf(path1) != -1){
> obj.data.uinfo["down_daily_remainders"] = "666";
> obj.data.uinfo["play_daily_remainders"] = "666";
> obj.data.uinfo["curr_group"] = "5";
> obj.data.user["isvip"] = "1";
> obj.data.user["goldcoin"] = "666";
> }
> 
> if ($request.url.indexOf(ad) != -1) {
> delete obj.data.pmap
> }
> $done({body: JSON.stringify(obj)});

好的，谢谢你提供的方法，已更新脚本
