### ISSUE TITLE
途虎qx好像获取不到cookies了

### ISSUE THREAD

**Issue by jaychoubaby** [photonmang/quantumultX#32]
今天开始，从途虎app获取不到cookies了，步骤全对，但是获取不到cookies了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by duadu624** [comment]
你好，我是杜榕剑。我已收到你的信息，我会尽快的查看。辛苦你啦，谢谢。
