### ISSUE TITLE
QQ阅读

### ISSUE THREAD

**Issue by shaGuar-svg** [photonmang/quantumultX#4]
使用BOXJS多账号运行，查看通知阅读时间一天只有150分钟的样子，是否执行有问题。11分钟执行一次。宝箱奖励好像也不对，这是正常的嘛？

**Comment by photonmang** [comment]
应该是你的问题，我这边于都时间每个号都超过300分钟以上，一天跑下来一般都有500左右或以上的阅读时间，具体没有去看。你设备中如果还有其他脚本，跑的比较多，是有可能影响到阅读时间的提交。可以尝试适当调整执行时间

**Comment by shaGuar-svg** [comment]
好的，我这边重新获取下COOKIE，走几次看看。感谢回复

**Comment by shaGuar-svg** [comment]
`
![8bfd948394c14627d5edad62f97e627](https://user-images.githubusercontent.com/55645390/101276686-97494080-37e9-11eb-9618-6fdbaaac0db8.jpg)
`运行日志是LOG显示：{} 这样也是正常的么

**Comment by shaGuar-svg** [comment]
2020/12/06 17:45:59:174  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, 
2020/12/06 17:46:00:014  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, https://raw.githubusercontent.com/photonmang/quantumultX/master/cache/qqreads.js
2020/12/06 17:46:00:224  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, 
2020/12/06 17:46:01:065  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, https://raw.githubusercontent.com/photonmang/quantumultX/master/cache/qqreads.js
2020/12/06 17:46:01:231  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, 
2020/12/06 17:46:02:001  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, https://raw.githubusercontent.com/photonmang/quantumultX/master/cache/qqreads.js
2020/12/06 17:46:02:197  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, 
2020/12/06 17:46:02:991  <error>      [JS Console]: Exception {}, ReferenceError: Can't find variable: task, https://raw.githubusercontent.com/photonmang/quantumultX/master/cache/qqreads.js

这是错误么？你仓库里3个文件我都试了，都会出现这种错误。

**Comment by shaGuar-svg** [comment]
@photonmang
