### ISSUE TITLE
多账号

### ISSUE THREAD

**Issue by minv5** [photonmang/quantumultX#6]
请问，boxjs也获取多账号了，但是运行的时候只运行其中一个账号，不知是哪里还需要设置吗？

**Comment by photonmang** [comment]
请获取cookie的时候，请务必要顺序获取。在获取cookie行内填写要获取的账号，如填写1，请务必保存后再去获取。再次获取第二个账号的时候，填写2，再保存设置。再次登陆第二个QQ账号去获取阅读cookie和时长，依次类推。请按步骤进行。否则您将一直只执行一个账号的循环。

**Comment by minv5** [comment]
> 请获取cookie的时候，请务必要顺序获取。在获取cookie行内填写要获取的账号，如填写1，请务必保存后再去获取。再次获取第二个账号的时候，填写2，再保存设置。再次登陆第二个QQ账号去获取阅读cookie和时长，依次类推。请按步骤进行。否则您将一直只执行一个账号的循环。

现在远程教程运行的是那一个？我看最新更新的是qqread

**Comment by minv5** [comment]
重新获取了一遍还是只运行最后一个保存的账号

**Comment by photonmang** [comment]
你检查下，是否使用的cookie的重写用的是本仓库的。如果是原作者的是不生效的。因没有写入变量，无法进行获取

**Comment by minv5** [comment]
是本仓库的   https:\/\/mqqapi\.reader\.qq\.com\/mqq\/user\/init    https:\/\/mqqapi\.reader\.qq\.com\/mqq\/addReadTimeWithBid?
https://raw.githubusercontent.com/photonmang/quantumultX/master/cache/qqread.js

**Comment by noelff** [comment]
强大
