### ISSUE TITLE
rewrite部分不能正确导入，手动修改就提示重复

### ISSUE THREAD

**Issue by xprears** [photonmang/quantumultX#9]
获取cookie的语句。
hostname可以正常导入

**Comment by photonmang** [comment]
cookie使用的是哪个重写脚本。cookie.conf的脚本刚刚已进行修复，去除一项重复的qq阅读老cookie。请重试下

**Comment by xprears** [comment]
https://raw.githubusercontent.com/photonmang/quantumultX/master/config/qxconfig.conf
导入的这个配置，单独导入cookie.conf 提示rewrite local部分复写

**Comment by photonmang** [comment]
这配置已经都集成了，不用另外再去加ck重写

**Comment by xprears** [comment]
但是没法获取cookie，这部分在哪里能看到？在rewrite local下是空的
